export function getCategoryName(id) {
    switch (id) {
      case 1:
        return '计算机科学'
      case 2:
        return '社会科学'
      case 3:
        return '电子科技'
      case 4:
        return '教育'
      case 5:
        return '工程'
      case 6:
        return '环境'
      case 7:
        return '地理'
      case 8:
        return '历史'
      case 9:
        return '法律'
      case 10:
        return '生活科学'
      case 11:
        return '共同关系'
      case 12:
        return '爆炸'
      case 13:
        return '管理'
      case 14:
        return '地球科学'
      case 15:
        return '机械科学'
      case 16:
        return '数学'
      case 17:
        return '公共健康'
      case 18:
        return '生物'
      case 19:
        return '物理'
      case 20:
        return '不知道'
      case 21:
        return '心理学'
      case 22:
        return '国际关系'
    }
  }
  export function categoryText(category, vue) {
  switch (category) {
    case 1:
        return '计算机科学'
      case 2:
        return '社会科学'
      case 3:
        return '电子科技'
      case 4:
        return '教育'
      case 5:
        return '工程'
      case 6:
        return '环境'
      case 7:
        return '地理'
      case 8:
        return '历史'
      case 9:
        return '法律'
      case 10:
        return '生活科学'
      case 11:
        return '共同关系'
      case 12:
        return '爆炸'
      case 13:
        return '管理'
      case 14:
        return '地球科学'
      case 15:
        return '机械科学'
      case 16:
        return '数学'
      case 17:
        return '公共健康'
      case 18:
        return '生物'
      case 19:
        return '物理'
      case 20:
        return '不知道'
      case 21:
        return '心理学'
      case 22:
        return '国际关系'
  }
}
export const categoryList = {
  '计算机科学': 1,
  '社会科学': 2,
  '电子科技': 3,
  '教育': 4,
  '工程': 5,
  '环境': 6,
  '地理': 7,
  '历史': 8,
  '法律': 9,
  '生活科学': 10,
  '共同关系': 11,
  '爆炸': 12,
  '管理': 13,
  '地球科学': 14,
  '机械科学': 15,
  '数学': 16,
  '公共健康': 17,
  '生物': 18,
  '物理': 19,
  '不知道': 20,
  '心理学': 21,
  '国际关系': 22
}